# Generated by Django 4.1.7 on 2023-09-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kelompok',
        ),
    ]
