# Generated by Django 4.1.7 on 2023-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_kelompok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('kode_kelompok', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_kelompok', models.CharField(max_length=30)),
                ('usertime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
