# Generated by Django 4.2.5 on 2023-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mapotik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapotik',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
