# Generated by Django 4.2.5 on 2023-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_msatuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdafsat',
            fields=[
                ('kode_daftar_satuan', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('satuan_terbesar', models.CharField(max_length=100)),
                ('satuan_sedang', models.CharField(max_length=100)),
                ('satuan_terkecil', models.CharField(max_length=100)),
                ('jumsat_terbesar', models.CharField(max_length=50)),
                ('jumsat_sedang', models.CharField(max_length=50)),
                ('jumsat_terkecil', models.CharField(max_length=50)),
            ],
        ),
    ]
