# Generated by Django 4.2.5 on 2023-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mdafsat'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbarang',
            fields=[
                ('kode_barang', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_barang_lengkap', models.CharField(max_length=100)),
                ('nama_barang_penjualan', models.CharField(max_length=100)),
                ('jenis_barang', models.CharField(max_length=100)),
                ('satua_terkecil', models.CharField(max_length=50)),
                ('barcode_terkecil', models.CharField(max_length=20)),
                ('harga_pl_sebelum_ppn', models.CharField(max_length=100)),
                ('harga_pl_sesudah_ppn', models.CharField(max_length=100)),
                ('harga_pokok_penjualan', models.CharField(max_length=100)),
                ('margin_penjualan', models.CharField(max_length=50)),
                ('harga_penjualan_sat_terkecil', models.CharField(max_length=100)),
                ('tanggal_update_terakhir', models.DateTimeField(auto_now=True)),
                ('kode_dafar_satuan', models.CharField(max_length=4)),
                ('status_aktif_barang', models.CharField(default='y', max_length=1)),
                ('usertime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
