# Generated by Django 4.2.5 on 2023-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id_admin', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telepon', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
