# Generated by Django 4.2.5 on 2023-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_mbarang_usertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbarang',
            name='usertime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
