# Generated by Django 4.1.7 on 2023-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_mprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mprofil',
            name='gambar',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
