# Generated by Django 4.2.5 on 2023-09-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_mbarang_status_aktif_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbarang',
            name='status_aktif_barang',
            field=models.CharField(choices=[('Y', 'Y'), ('T', 'T')], default='Y', max_length=1),
        ),
    ]
