# Generated by Django 4.2.5 on 2023-09-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_mbarang_status_aktif_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='telepon',
        ),
    ]
