# Generated by Django 4.2.5 on 2023-09-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_admin_email_remove_admin_telepon'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbrgsat',
            fields=[
                ('kode_barang', models.CharField(max_length=4)),
                ('kode_satuan', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('harga_pl_sebelum_ppn', models.CharField(max_length=100)),
                ('harga_pl_sesudah_ppn', models.CharField(max_length=100)),
                ('qty_satuan_terkecil', models.CharField(max_length=100)),
                ('tanggal_update_terakhir', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=20)),
                ('usertime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
