# Generated by Django 4.2.5 on 2023-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_mbrgsat'),
    ]

    operations = [
        migrations.CreateModel(
            name='msupplier',
            fields=[
                ('kode_supplier', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=50)),
                ('npwp', models.CharField(max_length=20)),
                ('status_pkp', models.CharField(choices=[('Y', 'Y'), ('T', 'T')], default='Y', max_length=1)),
                ('alamat', models.CharField(max_length=100)),
                ('nomor_telp', models.CharField(max_length=20)),
                ('kontak_person_cp', models.CharField(max_length=20)),
                ('kontak_hp_cp', models.CharField(max_length=20)),
                ('nama_bank', models.CharField(max_length=30)),
                ('nomor_rekening', models.CharField(max_length=30)),
                ('periode_kunjungan', models.DateField()),
                ('periode_pembayaran_kredit', models.DateField()),
                ('keterangan_supplier', models.CharField(max_length=200)),
                ('status_aktif_supllier', models.CharField(choices=[('Y', 'Y'), ('T', 'T')], default='Y', max_length=1)),
                ('usertime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
